export var EndPoints={
    Host : "https://covidserve.azurewebsites.net/api/",
        fetchCountry:"fetchCountry?", 
        fetchCountryNames:"fetchCountryNames?", 
        fetchCountryOnDate:"fetchCountryOnDate?", 
        fetchCountryToday:"fetchCountryToday?", 
        fetchOnDate:"fetchOnDate?", 
        fetchTopActiveCount:"fetchTopActiveCount?", 
        fetchTopConfirmedCount:"fetchTopConfirmedCount?", 
        fetchTopDeathCount:"fetchTopDeathCount?", 
        fetchTopRecoveredCount:"fetchTopRecoveredCount?", 

        fetchTopNewCases:"fetchTopNewCases?", 
        fetchTopNewDeaths:"fetchTopNewDeaths?", 
        fetchTopNewRecoveries:"fetchTopNewRecoveries?", 

        fetchSortedActiveCount:"fetchSortedActiveCount?", 
        fetchSortedConfirmedCount:"fetchSortedConfirmedCount?", 
        fetchSortedDeathCount:"fetchSortedDeathCount?", 
        fetchSortedRecoveredCount:"fetchSortedRecoveredCount?", 
        fetchSortedNewCases:"fetchSortedNewCases?", 
        fetchSortedNewDeaths:"fetchSortedNewDeaths?", 
        fetchSortedNewRecoveries:"fetchSortedNewRecoveries?", 
        fetchCountryActive:"fetchCountryActive?", 
        fetchCountryConfirmed:"fetchCountryConfirmed?", 
        fetchCountryDeath:"fetchCountryDeath?", 
        fetchCountryNewCases:"fetchCountryNewCases?", 
        fetchCountryNewDeaths:"fetchCountryNewDeaths?", 
        fetchCountryNewRecoveries:"fetchCountryNewRecoveries?", 
        fetchCountryRecovered:"fetchCountryRecovered?",
}